### ISSUE TITLE
Атрибут alt в компоненте img ошибочно указан как класс.

### ISSUE THREAD

**Issue by KurlenkovEvgeniy** [tdkomplekt/laravel-bootstrap-components#3]
Из-за этого атрибут alt не отображаетя.
Достаточно убрать строку
https://github.com/tdkomplekt/laravel-bootstrap-components/blob/616b2fd9ce374b80a00f45b82d51f612d378edc1/resources/views/components/img.blade.php#L19C8-L19C23

**Comment by tdkomplekt** [comment]
https://github.com/tdkomplekt/laravel-bootstrap-components/releases/tag/1.2.2
